marcosbarbero/spring-cloud-zuul-ratelimit

src/main/java/com/marcosbarbero/zuul/filters/pre/ratelimit/RateLimitFilter.java
It deals with a route without policies letting these routes pass through the filter directly.
=> Making policy per route optional

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/DefaultRateLimitKeyGenerator.java
Fixes #28 
- check that the route is not null
=> added a check if route exists

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/DefaultRateLimitKeyGenerator.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/DefaultRateLimitKeyGeneratorTest.java
- Added missing tests for `DefaultRateLimitKeyGenerator`
=> added missing tests

.travis.yml
Fixes #30 
- Sonar code coverage analyses
=> Add sonar coverage check

README.md, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/RateLimitAutoConfiguration.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/AbstractRateLimitFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPostFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPreFilter.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/RateLimitAutoConfigurationTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/post/RateLimitPostFilterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/BaseRateLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/ConsulRateLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/RateLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/RedisRateLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-tests/consul/src/test/java/com/marcosbarbero/tests/it/ConsulApplicationTestIT.java, spring-cloud-zuul-ratelimit-tests/inmemory/src/test/java/com/marcosbarbero/tests/it/InMemoryApplicationTestIT.java, spring-cloud-zuul-ratelimit-tests/redis/src/test/java/com/marcosbarbero/tests/it/RedisApplicationTestIT.java, spring-cloud-zuul-ratelimit-tests/springdata/src/test/java/com/marcosbarbero/tests/it/SpringDataApplicationTestIT.java
=> #40 Support multiple policies

.ci/deploy.sh, README.md, pom.xml, spring-cloud-starter-zuul-ratelimit/pom.xml, spring-cloud-zuul-ratelimit-core/pom.xml, spring-cloud-zuul-ratelimit-coverage/pom.xml, spring-cloud-zuul-ratelimit-dependencies/pom.xml, spring-cloud-zuul-ratelimit-tests/consul/pom.xml, spring-cloud-zuul-ratelimit-tests/inmemory/pom.xml, spring-cloud-zuul-ratelimit-tests/redis/pom.xml, spring-cloud-zuul-ratelimit-tests/springdata/pom.xml
=> Upgrade to Edgware.SR3

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPreFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/RateLimitExceededException.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/RateLimitExceededExceptionTest.java
=> #69 about ZuulRuntimeException - use specific exception instead of ZuulRuntimeException

README.adoc, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/AbstractRateLimitFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPostFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPreFilter.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitPropertiesTest.java
=> Move filters order to configuration

pom.xml, spring-cloud-starter-zuul-ratelimit/pom.xml, spring-cloud-zuul-ratelimit-core/pom.xml, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/springdata/JpaRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/springdata/JpaRateLimiterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/JpaLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-coverage/pom.xml, spring-cloud-zuul-ratelimit-dependencies/pom.xml, spring-cloud-zuul-ratelimit-tests/bucket4j-hazelcast/pom.xml, spring-cloud-zuul-ratelimit-tests/bucket4j-ignite/pom.xml, spring-cloud-zuul-ratelimit-tests/bucket4j-ignite/src/main/java/com/marcosbarbero/tests/Bucket4jIgniteApplication.java, spring-cloud-zuul-ratelimit-tests/bucket4j-infinispan/pom.xml, spring-cloud-zuul-ratelimit-tests/bucket4j-jcache/pom.xml, spring-cloud-zuul-ratelimit-tests/bucket4j-jcache/src/main/java/com/marcosbarbero/tests/Bucket4jJCacheApplication.java, spring-cloud-zuul-ratelimit-tests/consul/pom.xml, spring-cloud-zuul-ratelimit-tests/inmemory/pom.xml, spring-cloud-zuul-ratelimit-tests/redis/pom.xml, spring-cloud-zuul-ratelimit-tests/redis/src/main/java/com/marcosbarbero/tests/config/RedisConfig.java, spring-cloud-zuul-ratelimit-tests/springdata/pom.xml
Fixes #57
- Upgrade to Spring Boot 2 and Spring Cloud Finchley
=> Add Spring Cloud Finchley Support

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/DefaultRateLimitKeyGenerator.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/AbstractRateLimitFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPostFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPreFilter.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/DefaultRateLimitKeyGeneratorTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/post/RateLimitPostFilterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/BaseRateLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/ConsulRateLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/RedisRateLimitPreFilterTest.java
=> #89 A service with different interfaces has different policies

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/RateLimitUtils.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/DefaultRateLimitKeyGeneratorTest.java
=> Get the first IP from X-Forwarded-For list

pom.xml, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/RedisRateLimitPreFilterTest.java
=> Performance enhancement

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiterTest.java
=> Adds performance improvement for RedisRateLimiter

README.adoc, pom.xml, spring-cloud-zuul-ratelimit-tests/bucket4j-hazelcast/src/main/resources/application.yml, spring-cloud-zuul-ratelimit-tests/bucket4j-ignite/src/main/resources/application.yml, spring-cloud-zuul-ratelimit-tests/bucket4j-infinispan/src/main/resources/application.yml, spring-cloud-zuul-ratelimit-tests/bucket4j-jcache/src/main/resources/application.yml, spring-cloud-zuul-ratelimit-tests/consul/src/main/resources/application.yml, spring-cloud-zuul-ratelimit-tests/redis/src/main/resources/application.yml, spring-cloud-zuul-ratelimit-tests/springdata/src/main/resources/application.yml
Fixes the tests configuration removing deprecated properties
=> Fix tests configurations

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/RateLimitUtils.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/DefaultRateLimiterErrorHandler.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/bucket4j/AbstractBucket4jRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/bucket4j/Bucket4jHazelcastRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/bucket4j/Bucket4jIgniteRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/bucket4j/Bucket4jInfinispanRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/bucket4j/Bucket4jJCacheRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/springdata/JpaRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPostFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPreFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/DefaultRateLimitUtils.java
Polishing some variable/class modifiers
=> Minor refactoring

pom.xml, spring-cloud-zuul-ratelimit-core/pom.xml, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/RateLimitAutoConfiguration.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/RateLimitUtils.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitType.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/validators/PoliciesValidator.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/DefaultRateLimitUtils.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/SecuredRateLimitUtils.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/DefaultRateLimitKeyGeneratorTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitTypeTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/SecureContextRateLimitTypeTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/validators/PoliciesValidatorTest.java, spring-cloud-zuul-ratelimit-coverage/pom.xml, spring-cloud-zuul-ratelimit-tests/security-context/pom.xml, spring-cloud-zuul-ratelimit-tests/security-context/src/main/java/com/marcosbarbero/tests/SecurityContextApplication.java, spring-cloud-zuul-ratelimit-tests/security-context/src/main/java/com/marcosbarbero/tests/config/InMemoryRedisConfig.java, spring-cloud-zuul-ratelimit-tests/security-context/src/main/resources/application.yml, spring-cloud-zuul-ratelimit-tests/security-context/src/test/java/com/marcosbarbero/tests/it/SecurityContextApplicationTestIT.java, spring-cloud-zuul-ratelimit-tests/security-context/src/test/resources/logback.xml
=> Add rate limiting based on user-role evalutation

README.adoc, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitType.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/DefaultRateLimitKeyGeneratorTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitTypeTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/validators/PoliciesValidatorTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/BaseRateLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/StringToMatchTypeConverterTest.java
Fixes #135 
- Add RateLimitType.METHOD
- Test RateLimitType.METHOD
- Remove unuesed imports in test case by git commit.
=> Feature RateLimitType.METHOD

README.adoc, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPreFilter.java
- custom hide or show header in response
=> custom hide or show header in response

README.adoc
Fixes #158 
- Updates the README file adding a reference to the right version based on Spring Boot's version used.
=> Update README.adoc (#159)[ci skip]

README.adoc, spring-cloud-zuul-ratelimit-core/pom.xml, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/Rate.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/AbstractRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/ConsulRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/DefaultRateLimiterErrorHandler.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/AbstractRateLimitFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/DefaultRateLimitKeyGenerator.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/DefaultRateLimitUtils.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/RateLimitConstants.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/commons/TestRouteLocator.java
=> Remove lombok dependency

.travis.yml, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPreFilter.java
=> Add add-response-headers config property

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java
#fix: redisRemainingQuota for  #200
=> #fix: redisRemainingQuota

pom.xml, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/RateLimitAutoConfigurationTest.java
Adds unit tests and exclude POJO from code coverage
=> Add unit tests and exclude POJO from code coverage

README.adoc
Change the phrasing and add a footnote to the readme
Fixes #
- Change the phrasing of the README.adoc
-
-
=> Rephrase the error handling explanation and add a footnote [ci skip]

README.adoc
Fixes #241 
- Improve JPA documentation
=> Add JPA's require table doc

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/AbstractRateLimitFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/RateLimitConstants.java
=> Add alreadyLimited to the request context

.gitignore, pom.xml, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiterTest.java
Fixes #162
As suggested by @alowrey, I replaced the  increment + expire commands with setIfAbsent + increment.
=> Fix race condition in redis limiter

.travis.yml, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/RateLimitAutoConfiguration.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/RedisRateLimitPreFilterTest.java
Fixes #268 
- Uses `StringRedisTemplate` instead of `RedisTemplate`
=> Fix RedisTemplate Casting Exception

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/resources/scripts/ratelimit.lua, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/BaseRateLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/RedisRateLimitPreFilterTest.java
Fixes #311 
- Adds a Lua script for Redis operations
=> Add Lua Script to perform Redis Operations

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/RedisRateLimiter.java
- Currently, the lua script is read on every request.
- So, I changed the redis lua script to read only once
=> Change redis lua script read once

spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPreFilter.java
=> Fix header verbosity conditional

.github/workflows/greetings.yml, README.adoc, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/repository/AbstractRateLimiter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/AbstractRateLimitFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/RateLimitPreFilter.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/support/RateLimitExceededException.java, spring-cloud-zuul-ratelimit-core/src/test/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/pre/RateLimitPreFilterTest.java, spring-cloud-zuul-ratelimit-tests/springdata/src/main/resources/application.yml, spring-cloud-zuul-ratelimit-tests/springdata/src/test/java/com/marcosbarbero/tests/it/SpringDataApplicationTestIT.java, spring-cloud-zuul-ratelimit-tests/springdata/src/test/java/com/marcosbarbero/tests/it/SpringDataDenyOriginTestIT.java
Fixes #385 
Adds a way to deny requests from malicious origins.
=> Add request origin deny list

.github/workflows/codeql-analysis.yml, .travis.yml, pom.xml
Fixes #387 
- Migrates the codebase from Java 8 to Java 11
=> Migrate from Java 8 to Java 11

README.adoc, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/config/properties/RateLimitProperties.java, spring-cloud-zuul-ratelimit-core/src/main/java/com/marcosbarbero/cloud/autoconfigure/zuul/ratelimit/filters/AbstractRateLimitFilter.java, spring-cloud-zuul-ratelimit-tests/springdata/src/test/java/com/marcosbarbero/tests/it/SpringDataApplicationTestIT.java, spring-cloud-zuul-ratelimit-tests/springdata/src/test/java/com/marcosbarbero/tests/it/SpringDataDenyOriginTestIT.java
- Rename DenyList to DenyRequest
=> Rename DenyList to DenyRequest
